# Generated by Django 5.0.4 on 2024-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('language', models.TextField()),
                ('ratting', models.FloatField()),
                ('m_format', models.TextField()),
                ('duration', models.TextField()),
                ('genre', models.TextField()),
                ('r_date', models.DateField()),
                ('cover_image', models.FileField(upload_to='')),
                ('main_image', models.FileField(upload_to='')),
            ],
        ),
    ]
