# Generated by Django 5.0.4 on 2024-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image1',
            field=models.FileField(default='one', upload_to=''),
            preserve_default=False,
        ),
    ]
