# Generated by Django 5.0.4 on 2024-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='about',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
