# Generated by Django 5.0.4 on 2024-05-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
        ),
    ]
